### ISSUE TITLE
Error on load: TypeError: Cannot read properties of undefined (reading 'appendChild')

### ISSUE THREAD

**Issue by AKokos** [chantouchsek/vue-iframes#139]
Applied to version 0.0.19
Problem is here - /src/components/vue-iframe.vue (91):

`this.$el.appendChild(this.iframeEl);`

Reason:
this.$el is not exists until mounted

Previous (0.0.18) version is OK

**Comment by WillcoWD** [comment]
I'm getting 

```Uncaught TypeError: this.$el is null vue-iframes.js:56:15```

This is in version 0.0.20
