### ISSUE TITLE
this.$el is null

### ISSUE THREAD

**Issue by WillcoWD** [chantouchsek/vue-iframes#147]
Hi

I'm getting the following error

```
Uncaught TypeError: this.$el is null vue-iframes.js:56:15
```

I'm using Vue 3, my Vue file is

```
<script>

export default {

    data() {
        return {
            myIframe: null
        }
    },


    methods: {

        onLoad(frame) {
            this.myIframe = frame.contentWindow
        },

    }

}
</script>

<template>

        <vue-iframe :src="'https://google.com'" @load="onLoad" name="my-frame"></vue-iframe>

</template>
```

Thanks
Mark

**Comment by chantouchsek** [comment]
Did you try lower version than this?

**Comment by WillcoWD** [comment]
I tried v 0.0.19 and ran into https://github.com/chantouchsek/vue-iframes/issues/139

There was an error with v0.0.18 but can't remember what it was.

**Comment by chantouchsek** [comment]
I never try it in vue 3. did you try it in vue 2, is there the same issue?

**Comment by WillcoWD** [comment]
Vue3 is my first time using Vue. No idea how to setup Vue 2 :-(

**Comment by chantouchsek** [comment]
Ok, let give me sometime to investigate on vue 3.

**Comment by WillcoWD** [comment]
Thank you. Let me know if you need more information

**Comment by chantouchsek** [comment]
Yes, that's great. thanks for let me know about this.

**Comment by chantouchsek** [comment]
@WillcoWD I am so sorry, It doesn't support vue 3 now. I have to update the package.

**Comment by WillcoWD** [comment]
No problem. Thanks for looking
