### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by Lord-AY** [chantouchsek/vue-iframes#256]
Trying to use this component in Vue 3 causes issues @chantouchsek

**Comment by chantouchsek** [comment]
Yes, for now it suppose to work only with vue 2.

**Comment by Lord-AY** [comment]
Alright thank you

**Comment by Lord-AY** [comment]
If it's off any help, this is what I am currently using in my project, based off this codebase

`<script setup>
import { debounce } from "lodash";
import { ref, watch, onMounted, useAttrs } from "vue";

const props = defineProps({
  src: {
    type: String,
    required: true,
  },
  crossorigin: {
    type: String,
    default: "anonymous",
  },
  target: {
    type: String,
    default: "_parent",
  },
  className: {
    type: String,
    required: false,
  },
  allow: {
    type: String,
    default: "camera *; geolocation *; microphone *; autoplay *",
  },
  name: {
    type: String,
    default: "vue-iframes",
  },
  id: {
    type: String,
    default: "vue-iframes",
  },
  scrolling: { type: String },
  width: { type: [String, Number] },
  height: { type: [String, Number] },
});

const attrs = useAttrs();

const iframeEl = ref(null);
const containerEl = ref(null);

const removeIframe = () => {
  while (containerEl.value.firstChild) {
    containerEl.value.removeChild(containerEl.value.firstChild);
  }
};

const setIframeUrl = () => {
  if (!iframeEl.value.contentWindow) {
    initIframe();
  }
  // nextTick(() => {
  //   const iframeDoc = iframeEl.value.contentWindow.document;
  //   iframeDoc.open().write(`
  //       <body onload="window.location.href='${props.src}'; parent.postMessage('${iframeLoadedMessage}', '*')"></body>
  //       <script>
  //         window.document.onreadystatechange = function () {
  //           if (window.document.readyState === 'complete') {
  //             parent.postMessage('${iframeOnReadyStateChangeMessage}', '*')
  //           }
  //         };
  //       <\/script>
  //       `);
  //   iframeDoc.close();
  // });
};

const reinitIframe = debounce(function () {
  removeIframe();
  initIframe();
}, 200);

const initIframe = () => {
  iframeEl.value = document.createElement("iframe");

  iframeEl.value.setAttribute("id", props.id);
  iframeEl.value.setAttribute("frameborder", 0);

  if (props.scrolling)
    iframeEl.value.setAttribute("scrolling", props.scrolling);
  if (props.src) iframeEl.value.setAttribute("src", props.src);
  if (props.crossorigin)
    iframeEl.value.setAttribute("crossorigin", props.crossorigin);
  if (props.name) iframeEl.value.setAttribute("name", props.name);
  if (props.allow) iframeEl.value.setAttribute("allow", props.allow);
  if (props.width) iframeEl.value.setAttribute("width", props.width);
  if (props.height) iframeEl.value.setAttribute("height", props.height);
  if (props.target) iframeEl.value.setAttribute("target", props.target);
  if (props.className) iframeEl.value.setAttribute("class", props.className);

  for (const [key, value] of Object.entries(attrs)) {
    iframeEl.value.setAttribute(key, value);
  }

  containerEl.value.appendChild(iframeEl.value);
  setIframeUrl();
};

onMounted(() => {
  initIframe();
});

watch(
  () => props.src,
  () => reinitIframe(),
  { immediate: true }
);
</script>

<template>
  <div ref="containerEl"></div>
</template>
`

**Comment by chantouchsek** [comment]
@Lord-AY thank, it would be great if you have time to create a PR for that?

**Comment by Lord-AY** [comment]
I'm not too familiar with nuxt @chantouchsek

**Comment by TouchSek** [comment]
@Lord-AY ahh, got it. Let me handle it. by the way.
