### ISSUE TITLE
Error in component's created function but working fine if changed to mounted

### ISSUE THREAD

**Issue by eoto88** [chantouchsek/vue-iframes#349]
I'm wondering if I'm doing something wrong but I can't use the component without making a small change.

I get the error `TypeError: this.$el is undefined` when 'created' is fired in component VueIframe. If I change 'created' to 'mounted', everything seems to work properly.

If I understand Nuxt's lifecycle correctly, 'mounted' is fired after 'created' but, this.$el is only created after 'created' is fired.
https://v2.nuxt.com/docs/concepts/nuxt-lifecycle/

Thank you in advance :)

**Others infos**
![Screenshot from 2024-01-24 13-05-32](https://github.com/chantouchsek/vue-iframes/assets/3608231/154847d5-e615-4353-939b-8c7458704cee)

Tested on Nuxt 2.17.1 and 2.17.3 with SSR disabled

The module is included as documented :
`  modules: [
    ...
    'vue-iframes/nuxt',
  ],
`

**Comment by chantouchsek** [comment]
PR is Welcome 🙏 🤗
